
default: &default
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  strict: false
  username: postgres
  password: postgres
  timeout: 5000

development:
  <<: *default
  database: cognify_development

test:
  <<: *default
  database: cognify_test

production:
  <<: *default
  database: cognify_production
